### ISSUE TITLE
Not working with Playwright 1.30

### ISSUE THREAD

**Issue by wbartus** [elaichenkov/odottaa#188]
After updating Playwright from 1.29.2 to 1.30, I'm getting errors on first 'oddotta' function encounter i.e. toHaveJSON()

TypeError: this.customTesters is not iterable

at Object.toEqual (/node_modules/expect/build/matchers.js:752:15)
at Object.toHaveJSON (/node_modules/odottaa/lib/src/index.js:48:99)

**Comment by elaichenkov** [comment]
Hey @wbartus 

Thanks for creating an issue. I've just fixed the problem and released a new version with the fix. So, update the library to 1.1.10 and happy testing. Also, don't forget to give this repository a star.

**Comment by wbartus** [comment]
HI, 
Works with oddotta 1.1.13 and playwright 1.30. Thanks for super quick response!
