### ISSUE TITLE
Assert schemas with the union type and optional properties?

### ISSUE THREAD

**Issue by ataman1987** [elaichenkov/odottaa#207]
Hi! 👋 
Thx for sharing this package and describing the use case[ in the article](https://elaichenkov.medium.com/api-testing-with-playwright-odottaa-77451917342f). 🥇 

I'm playing around with Playwright since few weeks and the tool looks 🚀  Right now I'm researching options for API testing. So far so good. This morning I hit following case:

I have a local server running with some dummy API. There is a `GET` endpoint `/my/guitars` - no auth required. The endpoint returns an Array of guitars where a single object from an array has a schema that can be represented with the following types :

 ```typescript
export type Condition = 'New' | 'As good as new' | 'Good' | 'Used' | 'Damaged';

export type Guitar = {
  guitar: {
    manufacturer: string;
    model: string;
    buildYear: number;
    signedByFamousGuitarist: boolean;
    signedBy?: string | null; // optional parameter, once present can be string or null 
    condition: {
      keys: Condition;
      fretboard: Condition;
      front: Condition;
      back: Condition;
    };
  };
};

```
I've written example API test where I'm trying to assert the schema using methods provided in this package. I'm using `toContainJSON ()` for the assertion. To have more generic object for the assertion I'm using `expect.any()` for all of the properties. 

Here is the test:

```typescript
import { expect, test } from "@playwright/test";

test.describe("/get my guitars endpoint", () => {
  test("fetches all guitars and check schema", async ({ request }) => {
    const guitarSchema = {
      guitar: {
        manufacturer: expect.any(String),
        model: expect.any(String),
        buildYear: expect.any(Number),
        signedByFamousGuitarist: expect.any(Boolean),
        signedBy: null,
        condition: {
          keys: expect.any(String),
          fretboard: expect.any(String),
          front: expect.any(String),
          back: expect.any(String),
        },
      },
    };

    const response = await request.get("/my/guitars");

    expect(response).toHaveStatusCode(200);
    expect(response).toContainJSON(guitarSchema);
  });
});
```

The overall goal of the test would be to check if the API returns the object matching defined schema.

This test passed when returned response included optional parameter `signedBy` with value `null`:
```json
[
  {
    "guitar": {
      "buildYear": 2017,
      "condition": {
        "back": "As good as new",
        "fretboard": "As good as new",
        "front": "As good as new",
        "keys": "As good as new"
      },
      "manufacturer": "Maton",
      "model": "EBG808C W.A.",
      "signedBy": null,
      "signedByFamousGuitarist": false
    }
  }
]
```
With such object-schema in place (`const guitarSchema`) the are two scenarios when the test fails:

1. When `signedBy` value is a `String` 
2. When `signedBy` is not present in the response

I was trying to change the `const guitarSchema` definition and modify it to be able to accept both `null` and `string` values. I've tried this code:

```
 signedBy: null || expect.any(String)
``` 
and

```
 signedBy: expect.any(String || null)
``` 

None of this works. 

In fact this could only cover scenario where the parameter is either `null` or `String`. I guess allowing that would be sufficient for testing most of the API system. This is quite typical backend/API flow:  

1. entity is created in the database with some params, 
2. initial value of param `a` is set to `null`,
3. entity is returned via API as an object with param `a: null`
4. entity is modified (by the system or the user)
5. entity is returned in the API as an object with param `a` being `string`, `number` etc.

There might be also system which is not returning the param if the value is `null`.

Therefor I have 2 questions:
1. Is there any way to mark property in the object-schema ( `const guitarSchema` ) that allows more than one type with `expect.any()` or other syntax ?
2. Is there a way I could mark the `signedBy` param optional within the object-schema ( `const guitarSchema` )  definition? 

Ï would appreciate any suggestions. Thx!

**Comment by elaichenkov** [comment]
Hi Arthur,
Thank you for sharing your example and point of view. From my perspective, I think that schema validation will help you more to achieve your goals for this particular use case. So, I'd recommend you use some additional tools for that. For instance, [ajv](https://ajv.js.org/). Even more, as far as I know, there's no such ability to accomplish it with `expect.any()`. Howevere, I believe that it will be a good idea to add a schema validation tool to `odotta`.

**Comment by ataman1987** [comment]
> However, I believe that it will be a good idea to add a schema validation tool to odottaa. and have a new method toHaveSchema() or something like that.

That would be really nice 👍 

> So, I'd recommend you use some additional tools for that. For instance, [ajv](https://ajv.js.org/)

I followed Your advice and I was able to check the schema using ajv. I'm posting the solution If anyone would ever need it.


```typescript
import { expect } from "@playwright/test";
import Ajv, { JSONSchemaType } from "ajv";
import { test } from "../../../fixtures/loginFixture";

type Condition = "New" | "As good as new" | "Good" | "Used" | "Damaged";

type Guitar = {
  guitar: {
    manufacturer: string;
    model: string;
    buildYear: number;
    signedByFamousGuitarist: boolean;
    signedBy?: string | null; // optional parameter, once present can be string or null
    condition: {
      keys: Condition;
      fretboard: Condition;
      front: Condition;
      back: Condition;
    };
  };
};

/*
 * Create JSON schema based on provided Type in our case an Array of Guitars.
 * When schema is not matching Guitars type definition code editor highlights and error
 */

export const schema: JSONSchemaType<Guitar[]> = {
  type: "array",
  items: {
    type: "object",
    required: ["guitar"],
    additionalProperties: false,
    properties: {
      guitar: {
        type: "object",
        additionalProperties: false,
        required: [
          "manufacturer",
          "model",
          "signedByFamousGuitarist",
          "buildYear",
          "condition",
        ],
        properties: {
          signedBy: { type: "string", nullable: true },
          manufacturer: { type: "string" },
          model: { type: "string" },
          signedByFamousGuitarist: { type: "boolean" },
          buildYear: { type: "number" },
          condition: {
            additionalProperties: false,
            required: ["keys", "fretboard", "front", "back"],
            type: "object",
            properties: {
              keys: { type: "string" },
              fretboard: { type: "string" },
              front: { type: "string" },
              back: { type: "string" },
            },
          },
        },
      },
    },
  },
};

test.describe("/get my guitars endpoint", () => {
  test("fetches all guitars and check schema", async ({ request }) => {
    const ajv = new Ajv();
    const validate = await ajv.compile(schema);

    const response = await request.get("/my/guitars");
    const responseBody = await response.json();

    expect(response).toHaveStatusCode(200);

    if (validate(responseBody)) {
      // whatever You want to do if schema assertion is successful
    } else {
      // when schema assertion fails
      throw new Error("JSON Schema FATAL ERROR");
    }
  });
});

```

Make sure to include  `additionalProperties: false` to the schema - for strict assertions. Otherwise You might risk a false positive If API schema includes new params.

**Comment by elaichenkov** [comment]
Awesome, thank you for sharing!
