### ISSUE TITLE
odottaa has no default export

### ISSUE THREAD

**Issue by abodnar** [elaichenkov/odottaa#266]
Recently working with Playwright and saw that odottaa adds some helpful assertions. So I decided I'd give it a try and see if I liked it.

After installing and following the instructions to add it to my playwright.config.ts. 

```
import { defineConfig, devices, expect } from '@playwright/test';
import playwrightApiMatchers from 'odottaa';
```

My IDE Is warning me about this. `TS1192: Module '"/node_modules/odottaa/lib/src/index"' has no default export.`

Doesn't seem to cause an issue, but would be nice if this didn't show as an issue on that file.

**Comment by elaichenkov** [comment]
Hey @abodnar 
Thank you for using the library. That's weird. Can you please provide more details(os, typescript, playwright, odotta versions) on it? It would be fantastic if you could add a working example.

**Comment by abodnar** [comment]
Appreciate you looking into it. The more I've played with Playwright, the more I'm not sure it is the right tool for API testing.
