### ISSUE TITLE
Cant use toHaveHeaders for single header + value verification

### ISSUE THREAD

**Issue by qa-senpai** [elaichenkov/odottaa#352]
**Steps to reproduce**
const response: APIResponse = await request.post(`https://reqres.in/api/users`, {
      data: 
        {
            "name": "morpheus",
            "job": "leader"
        },
      failOnStatusCode: true,
    });

await expect(response).toHaveHeaders({'Connection': 'close'});

**Actual result**
fails with 
- Expected  -  1
+ Received  + 14

  Object {
-   "Connection": "close",
+   "access-control-allow-origin": "*",
+   "cf-cache-status": "DYNAMIC", .... }

**Expected result**
toHaveHeaders can be used to verify part of headers object, not all object.

or to add new matcher that will verify part of the headers object.

**Comment by elaichenkov** [comment]
Hey @qa-senpai,

Thank you for reporting the issue. You can use the `toHaveHeaderName` method. For instance:

```js
// Asserts that the response's headers contains the header 'Connection' with value 'close'
await expect(response).toHaveHeaderName('Connection', 'close');
```

Don't forget to give a star for the project.

**Comment by qa-senpai** [comment]
> ```js
> 'Connection', 'close'
> ```

What am I doing wrong? 
Property 'toHaveHeaderName' does not exist on type 'MakeMatchers<void, APIResponse

![Screenshot 2023-12-01 at 16 57 57](https://github.com/elaichenkov/odottaa/assets/95776140/c5da9e00-9d3a-47bc-83da-b32d32391449)

"odottaa": "^1.1.18"

**Comment by elaichenkov** [comment]
Sorry, my bad. It should be `toHaveHeader`

```js
// Asserts that the response's headers contains the header 'Connection' with value 'close'
await expect(response).toHaveHeader('Connection', 'close');
```

**Comment by qa-senpai** [comment]
> Sorry, my bad. It should be `toHaveHeader`
> 
> ```js
> // Asserts that the response's headers contains the header 'Connection' with value 'close'
> await expect(response).toHaveHeader('Connection', 'close');
> ```

but If want verify more then one header + value (but not all) ,  
e.g 
{
  'Connection': 'close',
 "access-control-allow-origin": "*",
 "cf-cache-status": "DYNAMIC"
}

**Comment by qa-senpai** [comment]
> For this case, you can use `toHaveHeaders`. It should work. I've just verified it.
> 
> ```js
> import { test, expect } from '@playwright/test';
> 
> test('verify toHaveHeaders', async ({ request }) => {
>   const response = await request.get('/');
>   console.log(response.headers());
> 
>   /**
>    * {
>       'content-type': 'text/html',
>       location: 'http://localhost:3000/',
>       date: 'Fri, 01 Dec 2023 15:24:36 GMT',
>       connection: 'close',
>       'content-length': '22
>    * }
>    * 
>    */
>   await expect(response).toHaveHeaders({ connection: 'close', 'content-length': '22' });
> });
> ```
> 
> <img alt="image" width="1020" src="https://private-user-images.githubusercontent.com/29764053/287307137-b0f46fb9-d4a9-46ae-a21a-0a9288c04ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDU3MzcsIm5iZiI6MTcwMTQ0NTQzNywicGF0aCI6Ii8yOTc2NDA1My8yODczMDcxMzctYjBmNDZmYjktZDRhOS00NmFlLWEyMWEtMGE5Mjg4YzA0YmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE1NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMWMxYWY3MjlhZDY0OTM5YjMwOTIwNmIyYzlmMmE0MDZkODc5ZGQwYzhkZDhlMjFiZWIwMmRlODJiZDBiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Afzqta3QadpUsYXXMGmaz4cjxn7HOSYLLhw_ZgYSBu8">

OMG, it really works... I think problem was that I use uper case in header name... :( 
Thank you :)
